# 1. Les imports & le code de base Mediapipe

In [7]:
import mediapipe as mp  # Import mediapipe
import cv2  # Import opencv
import csv
import os
import numpy as np

mp_drawing = mp.solutions.drawing_utils  # Drawing helpers
mp_holistic = mp.solutions.holistic  # Mediapipe Solutions

In [3]:
cap = cv2.VideoCapture(0)
# Initiate holistic model
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:

    while cap.isOpened():
        ret, frame = cap.read()

        # Recolor Feed
        image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        image.flags.writeable = False

        # Make Detections
        results = holistic.process(image)
        # print(results.face_landmarks)

        # face_landmarks, pose_landmarks, left_hand_landmarks, right_hand_landmarks

        # Recolor image back to BGR for rendering
        image.flags.writeable = True
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

        # 1. Draw face landmarks
        mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_TESSELATION,
                                  mp_drawing.DrawingSpec(
                                      color=(80, 110, 10), thickness=1, circle_radius=1),
                                  mp_drawing.DrawingSpec(
                                      color=(80, 256, 121), thickness=1, circle_radius=1)
                                  )

        # 2. Right hand
        mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS,
                                  mp_drawing.DrawingSpec(
                                      color=(80, 22, 10), thickness=2, circle_radius=4),
                                  mp_drawing.DrawingSpec(
                                      color=(80, 44, 121), thickness=2, circle_radius=2)
                                  )

        # 3. Left Hand
        mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS,
                                  mp_drawing.DrawingSpec(
                                      color=(121, 22, 76), thickness=2, circle_radius=4),
                                  mp_drawing.DrawingSpec(
                                      color=(121, 44, 250), thickness=2, circle_radius=2)
                                  )

        # 4. Pose Detections
        mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS,
                                  mp_drawing.DrawingSpec(
                                      color=(245, 117, 66), thickness=2, circle_radius=4),
                                  mp_drawing.DrawingSpec(
                                      color=(245, 66, 230), thickness=2, circle_radius=2)
                                  )

        cv2.imshow('Raw Webcam Feed', image)

        if cv2.waitKey(10) & 0xFF == ord('q'):
            break

cap.release()
cv2.destroyAllWindows()


INFO: Created TensorFlow Lite XNNPACK delegate for CPU.


# 2. Exporter les données

### Préliminaires :

In [8]:
num_coords = 75 # nombre de points du corps + main gauche + main droite
# for landmark in results.right_hand_landmarks.landmark:
#     print(landmark, landmark.value)
landmarks = ['class']
for val in range(1, num_coords+1):
    landmarks += ['x{}'.format(val), 'y{}'.format(val),
                  'z{}'.format(val), 'v{}'.format(val)]

with open('coords.csv', mode='w', newline='') as f:
    csv_writer = csv.writer(
        f, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
    csv_writer.writerow(landmarks)


### Choix du mot :

In [3]:
path='mots/'
mot = 'adresse'

### Code :

a) Cherche les fichiers à analyser en fonction du mot

In [4]:
fichier =[]
for f in os.listdir(path):
    file_name, file_ext = os.path.splitext(f)
    testmot = file_name.split('-')
    if (testmot[0]==mot):
        # i=1
        fichier += [path + file_name + file_ext]
print(fichier)

['mots/adresse-05.mp4', 'mots/adresse-13.mp4', 'mots/adresse-07.mp4', 'mots/adresse-10.mp4', 'mots/adresse-15.mp4', 'mots/adresse-18.mp4', 'mots/adresse-14.mp4', 'mots/adresse-01.mp4', 'mots/adresse-03.mp4', 'mots/adresse-06.mp4', 'mots/adresse-09.mp4', 'mots/adresse-12.mp4', 'mots/adresse-00.mp4', 'mots/adresse-11.mp4', 'mots/adresse-17.mp4', 'mots/adresse-04.mp4', 'mots/adresse-02.mp4', 'mots/adresse-16.mp4', 'mots/adresse-19.mp4', 'mots/adresse-08.mp4']


b) Parcourt les vidéos et exporte les coordonnées

In [9]:
rang = 0
for f in fichier :
    #print(f)
    cap = cv2.VideoCapture(f)
    # Initiate holistic model
    with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
        
        while cap.isOpened():
            ret, frame = cap.read()
            if ret:
                # Recolor Feed
                image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                image.flags.writeable = False        
                
                # Make Detections
                results = holistic.process(image)
                # print(results.face_landmarks)
                
                # face_landmarks, pose_landmarks, left_hand_landmarks, right_hand_landmarks
                
                # Recolor image back to BGR for rendering
                image.flags.writeable = True   
                image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
                
                # 1. Draw face landmarks
                mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_TESSELATION, 
                                        mp_drawing.DrawingSpec(color=(80,110,10), thickness=1, circle_radius=1),
                                        mp_drawing.DrawingSpec(color=(80,256,121), thickness=1, circle_radius=1)
                                        )
                
                # 2. Right hand
                mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                                        mp_drawing.DrawingSpec(color=(80,22,10), thickness=2, circle_radius=4),
                                        mp_drawing.DrawingSpec(color=(80,44,121), thickness=2, circle_radius=2)
                                        )

                # 3. Left Hand
                mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                                        mp_drawing.DrawingSpec(color=(121,22,76), thickness=2, circle_radius=4),
                                        mp_drawing.DrawingSpec(color=(121,44,250), thickness=2, circle_radius=2)
                                        )

                # 4. Pose Detections
                mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS, 
                                        mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=4),
                                        mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2)
                                        )
                # Export coordinates
                pose_row =[]
                right_hand_row=[]
                left_hand_row=[]
                try:
                    # Extract Pose landmarks
                    pose = results.pose_landmarks.landmark
                    pose_row = list(np.array([[landmark.x, landmark.y, landmark.z, landmark.visibility] for landmark in pose]).flatten())
                    #print(np.array([[landmark.x, landmark.y, landmark.z, landmark.visibility] for landmark in pose]))
                except : 
                    pass 
                try :
                        # Extract hands landmarks
                    right_hand = results.right_hand_landmarks.landmark
                    right_hand_row = list(np.array([[landmark.x, landmark.y, landmark.z, landmark.visibility] for landmark in right_hand]).flatten())
                except:
                    pass
                try:
                    left_hand = results.left_hand_landmarks.landmark
                    left_hand_row = list(np.array([[landmark.x, landmark.y, landmark.z, landmark.visibility] for landmark in left_hand]).flatten())
                except :
                    pass
                    # Concate rows
                row = pose_row + right_hand_row + left_hand_row
                
                # Append class name 
                row.insert(0, mot + format(rang))
                
                # Export to CSV
                with open('coords.csv', mode='a', newline='') as f:
                    csv_writer = csv.writer(f, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
                    csv_writer.writerow(row) 
                                
                cv2.imshow('Raw Webcam Feed', image)

                if cv2.waitKey(10) & 0xFF == ord('q'):
                    break
            else :
                break
    rang += 1
    cap.release()
    cv2.destroyAllWindows()

INFO: Created TensorFlow Lite XNNPACK delegate for CPU.


[[ 5.42599976e-01  2.36882985e-01 -8.93578291e-01  9.99968171e-01]
 [ 5.60671806e-01  1.95144773e-01 -8.40962827e-01  9.99959707e-01]
 [ 5.71493745e-01  1.94715559e-01 -8.41237307e-01  9.99958038e-01]
 [ 5.80100060e-01  1.95723176e-01 -8.40990067e-01  9.99937654e-01]
 [ 5.24070382e-01  1.99861348e-01 -8.29013646e-01  9.99946952e-01]
 [ 5.13028860e-01  2.02197015e-01 -8.29103649e-01  9.99945879e-01]
 [ 5.01420438e-01  2.05795825e-01 -8.29492390e-01  9.99927878e-01]
 [ 6.00732028e-01  2.23343372e-01 -5.12953281e-01  9.99944806e-01]
 [ 4.91937876e-01  2.37261653e-01 -4.58544821e-01  9.99925613e-01]
 [ 5.69545031e-01  2.80538857e-01 -7.77617335e-01  9.99979734e-01]
 [ 5.23217559e-01  2.85080910e-01 -7.62706459e-01  9.99975204e-01]
 [ 6.94741488e-01  5.26822507e-01 -3.56259376e-01  9.99240637e-01]
 [ 4.28038597e-01  5.45975208e-01 -1.81395322e-01  9.98745203e-01]
 [ 7.43412912e-01  9.15378511e-01 -6.68056309e-01  9.31761444e-01]
 [ 3.65495235e-01  9.05075610e-01 -3.97842824e-01  8.32533360e